/*
NomeObjeto: MOVAUP
TipoObjeto: TABLE
NomeTabela: MOVAUP
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE MOVAUP 
(
  RESOURCEID VARCHAR2(60 BYTE) NOT NULL 
, TIPO VARCHAR2(2 BYTE) NOT NULL 
, PROCEDURELINHA VARCHAR2(40 BYTE) 
, PROCEDUREFINAL VARCHAR2(40 BYTE) 
, EVENTOANT VARCHAR2(40 BYTE) 
, CONSTRAINT MOVAUP_PK PRIMARY KEY 
  (
    RESOURCEID 
  , TIPO 
  )
)

/

/*
NomeObjeto: MOVACB
TipoObjeto: TABLE
NomeTabela: MOVACB
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE MOVACB 
(
  IDMOV NUMBER(*, 0) NOT NULL 
, DESCRPROC VARCHAR2(40 BYTE) 
, CONDICAO VARCHAR2(400 BYTE) 
, ATIVO VARCHAR2(2 BYTE) 
, INSTANCIA VARCHAR2(40 BYTE) 
, CODINST NUMBER(*, 0) 
, EXPRESSAO VARCHAR2(400 BYTE) 
, CODINSTFILHA NUMBER 
, TRANSIENTFILTER VARCHAR2(4000 BYTE) 
, PROCEDUREFINAL VARCHAR2(20 BYTE) 
, CONSTRAINT MOVACB_PK PRIMARY KEY 
  (
    IDMOV 
  )
 )
/

/*
NomeObjeto: MOVAIT
TipoObjeto: TABLE
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE MOVAIT 
(
  IDMOV NUMBER(*, 0) NOT NULL 
, CODTIPOPER VARCHAR2(100 BYTE) NOT NULL 
, CODTIPVENDA VARCHAR2(100 BYTE) 
, CODNAT VARCHAR2(100 BYTE) 
, CODCENCUS VARCHAR2(100 BYTE) 
, CODEMP VARCHAR2(100 BYTE) 
, CODLOCAL VARCHAR2(100 BYTE) 
, CODPARC VARCHAR2(100 BYTE) 
, ORDEM NUMBER(*, 0) NOT NULL 
, ATIVO VARCHAR2(2 BYTE) 
, FAT VARCHAR2(2 BYTE) 
, OBSERVACAO VARCHAR2(4000 BYTE) 
, SERIENOTA VARCHAR2(100 BYTE) 
, FILTRO VARCHAR2(100 BYTE) 
, INSTANCIAFILHA VARCHAR2(40 BYTE) 
, CODINSTFILHA NUMBER 
, EXPRESSAO VARCHAR2(4000 BYTE) 
, TRANSIENTFILTER VARCHAR2(4000 BYTE) 
, INSTANCIA VARCHAR2(100 BYTE) 
, CODPROD VARCHAR2(100 BYTE) 
, QTDNEG VARCHAR2(100 BYTE) 
, CONTROLE VARCHAR2(100 BYTE) 
, VLRUNIT VARCHAR2(100 BYTE) 
, VLRDESC VARCHAR2(100 BYTE) 
, CONSTRAINT MOVAIT_PK PRIMARY KEY 
  (
    IDMOV 
  , ORDEM 
  )
)

/

/*
NomeObjeto: MOVAGE
TipoObjeto: TABLE
NomeTabela: MOVAGE
Executar  : SE_NAO_EXISTIR
*/ 

CREATE TABLE MOVAGE 
(
  ENTITYNAME VARCHAR2(100 BYTE) NOT NULL 
, PKQUERY VARCHAR2(200 BYTE) NOT NULL 
, IDMOV NUMBER(*, 0) NOT NULL 
, SEQUENCIA NUMBER(*, 0) NOT NULL 
, NUNOTA NUMBER(*, 0) 
, NUNOTAFAT NUMBER(*, 0) 
, CONSTRAINT MOVAGE_PK PRIMARY KEY 
  (
    ENTITYNAME 
  , IDMOV 
  , SEQUENCIA 
  , PKQUERY 
  )
 )
/

/*
NomeObjeto: CODEMPNEGOC
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD CODEMPNEGOC VARCHAR2(100) 
/

/*
NomeObjeto: CODLOCALDEST
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD CODLOCALDEST VARCHAR2(100) 
/

/*
NomeObjeto: OBSERVACAO
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD OBSERVACAO VARCHAR2(100) 
/

/*
NomeObjeto: USAPRECOTOP
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD USAPRECOTOP VARCHAR2(2) 
/

/*
NomeObjeto: NAOCONFIRMA
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD NAOCONFIRMA VARCHAR2(2)
/

/*
NomeObjeto: CODEMP_ITE
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD CODEMP_ITE VARCHAR2(100) 
/

/*
NomeObjeto: SEQUENCIA
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD SEQUENCIA VARCHAR2(100) 
/

/*
NomeObjeto: DIASRETCUSTO
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD DIASRETCUSTO FLOAT(126)
/

/*
NomeObjeto: CODEMP_CUS
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD CODEMP_CUS VARCHAR2(100) 
/

/*
NomeObjeto: COPYADDFIELDS
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD COPYADDFIELDS VARCHAR2(2) 
/

/*
NomeObjeto: TIPO
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD TIPO VARCHAR2(2) 
/

/*
NomeObjeto: COPYADDFIELDSCAB
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD COPYADDFIELDSCAB VARCHAR2(2) 
/

/*
NomeObjeto: ATRASAATUALEST
TipoObjeto: COLUMN
NomeTabela: TGFTOP
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFTOP 
ADD (ATRASAATUALEST VARCHAR2(2))
/

/*
NomeObjeto: FORCARETIRADESC
TipoObjeto: COLUMN
NomeTabela: TGFTOP
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFTOP 
ADD (FORCARETIRADESC VARCHAR2(2) )

/

/*
NomeObjeto: FORCAFATURANDO
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD FORCAFATURANDO VARCHAR2(2)
/

/*
NomeObjeto: FORCALIB
TipoObjeto: COLUMN
NomeTabela: TGFTOP
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFTOP 
ADD (FORCALIB VARCHAR2(2))

/

/*
NomeObjeto: CLAVLRDESC
TipoObjeto: COLUMN
NomeTabela: TGFITE
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE TGFITE ADD CLAVLRDESC FLOAT(126)
/

/*
NomeObjeto: NAOCONFIRMAFAT
TipoObjeto: COLUMN
NomeTabela: MOVAIT
Executar  : SE_NAO_EXISTIR
*/ 

ALTER TABLE MOVAIT ADD NAOCONFIRMAFAT VARCHAR2(2)
/

